### ISSUE TITLE
the code is shit

### ISSUE THREAD

**Issue by itslukej** [rem-bot-industries/nero#4]
pls rewrite thonks

**Comment by jacc** [comment]
ITS YA BOI

**Comment by jacc** [comment]
ITS YA BOI

**Comment by jacc** [comment]
bepis

**Comment by bjxke** [comment]
kekkekekekekekekekekekekkekekekekekekekekeke

**Comment by DasWolke** [comment]
get the heck away from my repo you hecks

**Comment by bjxke** [comment]
nao

**Comment by jacc** [comment]
OwO plz

**Comment by deansheather** [comment]
Good way to get yourselves blocked from the entire organization, keep it up if that's what you want to happen.
